[package]
name = "spiceai"
version = "3.2.0"
edition = "2024"
rust-version = "1.93.1"
description = "SDK for Spice.ai, an open-source runtime and platform for building AI-driven software."
license = "Apache-2.0"
repository = "https://github.com/spiceai/spice-rs"
homepage = "https://spice.ai"
documentation = "https://docs.rs/spiceai"
readme = "README.md"
keywords = ["spiceai", "sql", "arrow", "flight", "sdk"]
categories = ["api-bindings", "database"]

[dependencies]
arrow = { version = "58", features = ["prettyprint"] }
arrow-flight = { version = "58", features = ["flight-sql-experimental"] }
arrow-json = "58"
bytes = "1.6.0"
prost = { version = "0.14.1", features = ["derive"] }
prost-types = "0.14.1"
rustls = "0.23.5"
tokio = { version = "1.37.0", features = ["rt-multi-thread", "fs"] }
rustls-native-certs = "0.8.1"
tonic = { version = "0.14", default-features = false, features = [
  "transport",
  "tls-ring",
  "tls-native-roots",
] }
rustls-pemfile = "1.0.4"
reqwest = { version = "0.12.4", features = ["json", "rustls-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.116"
chrono = { version = "0.4.41", features = ["serde"] }
dotenv = "0.15.0"
futures = "0.3.31"
base64 = "0.22.0"
tracing = "0.1.41"
backoff = { version = "0.4.0", features = ["futures", "tokio"] }
rand = "0.9.1"
snafu = "0.8.5"

[target.'cfg(windows)'.dependencies]
winver = "1.0.0"

[dev-dependencies]
regex = "1.10.6"
wiremock = "0.6.5"
