name: crates-publish

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: cratesio
    permissions:
      id-token: write # Required for OIDC token exchange with crates.io
    steps:
      - uses: actions/checkout@v4

      - uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo build

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
