name: crates-publish

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run update
        run: rustup update && rustup default

      - run: cargo build --verbose

      - run: cargo test --verbose

      - run: cargo publish --verbose
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
