name: Publish to Crates.io

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Rust
      run:
        cargo publish  --token ${{ secrets.CRATES_IO_TOKEN }}